name: Build Virtualcam

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Cache Electron dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.cache/electron
                  key: ${{ runner.os }}-electron-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-electron-

            - name: Build for macOS and Windows
              run: |
                  npx electron-builder --mac --win
              env:
                  ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: dist
                  path: dist/
